travis:
  secure:
    BINSTAR_TOKEN: QHkZ4NoMSNTVR6lAVSimb7RhYxxPEAwDG7/8oqOJ8iBUJO99plw5C8oFzxnanPjImabTvqJ7im7mRx2RohgKD3mcRsi0rE3s/pNVgWnCxxwQFK0WMYKbBmSBFA3y+E1XVaQ/iq2oUSP1QuAUeb83vKz/mdOKExdQEY0MCq7kBE3uweJNfdkGY5De4Jit49funp5veEh6YEX0qo6EkImYDqPjIG2cO7OspCoHtbIG9mSPn7ro7rAf5Qf3FaA5wa5kFLtWP5+fA5PdZ7EqIrqZps1COT1qIC9AAJnSmoxO14pC8TqOXDhmdOlz0/ihnCZqRWtZLjrl1kgCsS/G8ld666QybizZO8mduk9gsDJMGDrAjfFjYRjE9F+mrMT4zEKByPaAmBeRF7fA8YxLGLj9b8nwq/WnZQ8+rz6DOXKGpHzMw+JXT3H14f5kdJKquqwdlNt52UQF3Gyd5/pHfATu7Dn5RS/RdmD9N20E7UpmbLSm272+d0tEnZVMr6+eIhrCyCPJf/UdNpek8awGrRWjcrs/jazgcdFPNR1LqQrnCDBZUKY79w61Xcidq5Ii6QusuYoWG1XYGeUQlxKRfhHWxcBFtpHBqXiwJ2uR9sRYGOw6nBveWCNiBiaplbrAVYQvpwJaTTqxMR7grHmik5LHik/beqUTNYv8PM9lqt4iuyE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
